### ISSUE TITLE
gui not starting after changing some settings and restarting

### ISSUE THREAD

**Issue by cisf** [qstokkink/TriblerExperimental#34]
[cisf-tribler-T9qhF9a7.log](https://github.com/qstokkink/TriblerExperimental/files/15141227/cisf-tribler-T9qhF9a7.log)
**Traceback and/or steps to reproduce**

```python
Insert your traceback here!
```
references to   jenkins  and not local machine
Traceback (most recent call last):
  File "/home/jenkins/workspace/workspace/Tribler/Build/Build-Ubuntu/tribler/build-env/lib/python3.8/site-packages/cx_Freeze/initscripts/__startup__.py", line 124, in run

**Comment by qstokkink** [comment]
Thank you for your report! I can reproduce this.

For some reason, saving the settings overwrites the following values in `~/.TriblerExperimental/configuration.json`:

```
"proxy_server": ":",
"proxy_auth": ":",
```

These values should have been:

```
"proxy_server": "",
"proxy_auth": "",
```

For now, the workaround is to manually set these values as stated above (to `""`) in a text editor.

I'll try to get a new build out as soon as possible to resolve this.

**Comment by qstokkink** [comment]
@cisf I created a new release to resolve this. You can find it here: https://github.com/qstokkink/TriblerExperimental/releases/tag/7.16.0-exp%2B003 

Please let me know if that does not fix your issue.
