### ISSUE TITLE
Loosing libray content?

### ISSUE THREAD

**Issue by Nubro01** [qstokkink/TriblerExperimental#71]
**Traceback and/or steps to reproduce**
Install this expirimental version
```python
Insert your traceback here!
```
After install and startup, my whole library was empty. 
If this is no bug, please add this warning within your anouncement!

**Comment by qstokkink** [comment]
Thanks for testing the experimental version!

Right now, the experimental version is in the testing phase so we're keeping all your files separated from "stable" Tribler, just to be safe. If you still want to copy over your old data, you can follow the steps detailed [here (click me)](https://github.com/qstokkink/TriblerExperimental/issues/31#issuecomment-2078814664).

**Comment by qstokkink** [comment]
I added a note to the forum post to explain this behavior (I even added it twice to make sure that nobody can miss is). With that, I hope the issue is sufficiently addressed.
